# try and except error
try:
    print(a)
except NameError as e:
    print("error",e)
except:
    print("i am except error")


